FROM ubuntu

RUN --mount=type=cache,id=ubuntu-apt-cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,id=ubuntu-apt-lists,target=/var/lib/apt,sharing=locked \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        curl git
    